// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEwWjbu3YSVEqIk7d5_1uwQzChY0kgLAY',
    appId: '1:729883295682:web:ab14b83a768ac992aea05b',
    messagingSenderId: '729883295682',
    projectId: 'local-service-vendor',
    authDomain: 'local-service-vendor.firebaseapp.com',
    storageBucket: 'local-service-vendor.firebasestorage.app',
    measurementId: 'G-GD0PM3DTL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDInbVK95V-8V2pSQTMi9-bVvqTVoTTMXM',
    appId: '1:729883295682:android:8e142b9db3e1a76daea05b',
    messagingSenderId: '729883295682',
    projectId: 'local-service-vendor',
    storageBucket: 'local-service-vendor.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEwWjbu3YSVEqIk7d5_1uwQzChY0kgLAY',
    appId: '1:729883295682:web:53ff06e7977995a9aea05b',
    messagingSenderId: '729883295682',
    projectId: 'local-service-vendor',
    authDomain: 'local-service-vendor.firebaseapp.com',
    storageBucket: 'local-service-vendor.firebasestorage.app',
    measurementId: 'G-10XTY565ES',
  );
}
