// services_data.dart
// Provider ke liye available services ki complete list

const List<String> kAvailableServices = [
  'Plumber',
  'Electrician',
  'Carpenter',
  'Painter',
  'AC Mechanic',
  'Refrigerator Mechanic',
  'Washing Machine Mechanic',
  'Mason / Construction Worker',
  'Tile Fitter',
  'Welder / Fabricator',
  'Gardener / Mali',
  'Driver',
  'Cook / Chef',
  'House Cleaner',
  'Tailor',
  'Barber / Hairdresser',
  'Beautician',
  'Computer Repair',
  'Mobile Phone Repair',
  'CCTV / Security Installation',
  'Pest Control',
  'Glasswork / Aluminium Work',
  'Roof Waterproofing',
  'Private Tutor',
  'Caregiver / Nurse Aid',
  'Laundry Service',
  'Delivery / Courier',
  'Event Setup',
  'Photographer',
  'Solar Panel Technician',
  'Generator Mechanic',
  'Water Pump Mechanic',
  'Flooring Specialist',
  'Interior Designer',
  'Security Guard',
];
